workflow commit

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -9,13 +9,13 @@ jobs:
       - name: say hello
         run: echo "Hello, world!"
   my-second-job:
-  runs-on: ubuntu-latest
-  steps:
-    - name: Failed step  #This exit 1 will fail,if the step fails, the whole workflow will fail.  Subsequent steps will not be executed by default
-      run: |
-        echo "I will fail"
-        exit 1   
-    - name: Say goodbye
-      run: echo "Goodbye!"
+    runs-on: ubuntu-latest
+    steps:
+      - name: Failed step  #This exit 1 will fail,if the step fails, the whole workflow will fail.  Subsequent steps will not be executed by default
+        run: |
+          echo "I will fail"
+          exit 1   
+      - name: Say goodbye
+        run: echo "Goodbye!"
 
 
